### ISSUE TITLE
Odd terminations of grain boundaries

### ISSUE THREAD

**Issue by j-m-dean** [ksyang2013/aimsgb#5]
I am attempting to use aimsgb to produce a large quantity of grain boundaries, however I have been obtaining odd terminations at the grain boundary. For example, for the anti-perovskite structure with sigma = 3, axis = (111), and plane = [1 1 1] the grain boundary output is one with oxygens in the centre of the grain boundary. See image

 <img width="714" alt="ap_odd_termination" src="https://user-images.githubusercontent.com/43647367/128130745-b85ae354-47e4-4c64-9272-dcbabe15fb65.png">. 

The correct structure can be produced by deleting the required layers ie "delete_layer = 1b1t1b1t". See image 

<img width="598" alt="ap_rectified" src="https://user-images.githubusercontent.com/43647367/128131050-e1070115-c2e6-403c-a163-368c8d7fee25.png"> 

Given that I wish to produce a large number of grain boundaries, manually visually inspecting what aimsgb is outputting, checking it is sensible, and then rectifying the terminations will likely take an exceedingly long time.

I produced the same grain boundary not too long ago with the correct termination behaviour using aimsgb, so I wonder if the route cause of the problem could have been recent software updates on one of the codes aimsgb is dependant on. 

The unit cell file I have been using to produce the grain boundaries is: 
[CONTCAR.zip](https://github.com/ksyang2013/aimsgb/files/6929025/CONTCAR.zip)

I have also noticed that the returned grain boundary for sigma = 3, axis = (210), and plane = [2 1 0] is identical to the grain boundary structure with the inputs sigma = 5, axis = (210), and plane = [2 1 0], which is not possible. 

Any help you could provide would be greatly appreciated.

**Comment by jic198** [comment]
Hello,

I don't think it is due to the recent update. I got the same oxygen
termination from my end. If you want to avoid certain terminations during
your production, one thing you can try is using grain.sort_sites_in_layers()
method. For example, after you define your GB:
gb = GrainBoundary([1, 1, 1], 3, [1, 1, 1], s)
You can do:
layers = gb.grain_a.sort_sites_in_layers()
Then you can check if the bottom, layers[0], or top layer, layers[-1], is
the oxygen layer. Then you can use gb.grain_a.delete_bt_layer to delete the
bottom or top layer. Let me know if this doesn't work.

Thanks,
Jianli

**Comment by j-m-dean** [comment]
Hello Jianli,

Thank you for the helpful advice and quick response. The above did work, thank you. 

Do you know why aimsgb produces the same grain boundary for sigma = 3, axis = (210), and plane = [2 1 0] and sigma  = 5, axis = (210), and plane = [2 1 0] ? Whilst I know that grain boundaries with the same sigma and different planes and axes may represent the same grain boundary, I thought it was impossible for grain boundaries with different sigma values to represent the same structure. 

Thanks,

Jacob

**Comment by jic198** [comment]
I apologize for the late reply. 
The reason for the two GBs to have the exact structure is because they have the same coincidence site lattice matrix. See below:
![image](https://github.com/ksyang2013/aimsgb/assets/18478036/b23ba939-78f1-490d-8176-a6ec9ad2ba1f)
Also, the structure of sigma 5[210]/(210) is the same with sigma 5[001]/(210)
