### ISSUE TITLE
No atoms in the grain boundary

### ISSUE THREAD

**Issue by Vaibhav51093** [ksyang2013/aimsgb#6]
Hi 

I am using this package for grain boundary generation. My question is regarding the restriction on the number of atoms. How can I define no of atoms?

**Comment by jic198** [comment]
I apologize for the late reply. 
There is no restriction on the number of atoms. Could you be more specific about your question? There are a number of ways to change the grain boundary size, like unit cell of each grain, etc.

**Comment by Vaibhav51093** [comment]
Hi Thanks , I have another question related to grain boundary creation for non-cubic crystal. I tried to create grain boundary using your tool but I fail to create it. My grain boundary was not stable. If you can help me with that then will be great help.

**Comment by jic198** [comment]
I recently improved the code to better deal with hexagonal and trigonal structures. However, the latest aimsgb may not be able to generate a GB from a rhombohedral, monoclinic or triclinic structure. The key is to make each grain orthogonal and I think it may be impossible for some low symmetry structures. You can try the `grain.set_orthognal_grain` function, but note that it would break inherent symmetries in the grain and I am not sure whether the generated GB makes sense. That's why I am hesitated to show it to the users. What happened when you used the normal approach? Did aimsgb hang there forever?

**Comment by Vaibhav51093** [comment]
THE INTERNAL SYMMETRY WAS BROKEN when I used the normal approach in Aimsgb to create GB for rhombohedral. I see one grain is stretched more than the other, and that is leading to strain in my grain boundary. I also figured out that this is the reason for the failure of my grain boundary. You are right that your software breaks internal symmetry and I also see that.

**Comment by jic198** [comment]
What's the version you used?

**Comment by Vaibhav51093** [comment]
Currently, I am using 'aimsgb 0.1.0'.

**Comment by jic198** [comment]
Could you try the newest 1.0.1? 
Also, if you don't mind, you can send me a structure and the type of GB you want to generate. I can test it from my end.

**Comment by Vaibhav51093** [comment]
Sure. May I get your email so that I can send you the structure? I need to create a twist and tilt grain boundary.

**Comment by jic198** [comment]
Here is my [email](chengjianli90@gmail.com).

**Comment by SUNWOUNG** [comment]
Hello,

As you know, the AIMSGB works to create grain boundary with (0,0,1) Σ5 [1,2,0] for our non-crystal structure. 
but, there is still a challenge.

As I understand, we can only get the GB information related to cubic. So, some of them cannot contribute to the CSL in our structure. The main problem is whether we cannot know whether there is no CSL in structure or it needs to take more time. Because it takes about 1 hour to generate GB. For example, in the case of (1,1,1) Σ3 [1,1,1], I stopped the algorithm after running for 5 days more. Therefore, I ask to you for notification if the algorithm cannot find CSL.

I appreciate for your attention to read this comment.
